config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :schedules
  root 'top#index'
  
  resource :schedules, only: [:new]
  resource :events, only: [:index, :show]
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/concerns/ai.rb
module Ai
  def self.classification(descriptions)
    Category.all.pluck('name')
  end
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/schedule.rb
class Schedule < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  include Ai
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook]
         
  acts_as_taggable_on :interests
  
  enum user_type: { guest: 0, host: 1 }
         
  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first
    
    unless user
      user = User.create(
        token:    auth.credentials.token,
        uid:      auth.uid,
        provider: auth.provider,
        email:    auth.info.email,
        image_url: auth.info.image,
        password: Devise.friendly_token[0, 20]
      )
    else
      user.update(token: auth.credentials.token)
    end
    
    graph = Koala::Facebook::API.new(user.token)
    events = graph.get_object("me?fields=events")
    descriptions = []
    events['events']['data'].each do |event|
      descriptions.push(event['description'])
    end
    
    if descriptions.present?
      user.interest_list = Ai.classification(descriptions)
      user.save
    end
    user
  end

  private

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end
end

app/models/user_category.rb
class UserCategory < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      #@event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.fetch(:event, {})
    end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.fetch(:schedule, {})
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_from :facebook
  end

  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
  
  def after_sign_in_path_for(resource)
    new_schedule_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/events/_form.html.slim
= form_for @event do |f|
  - if @event.errors.any?
    #error_explanation
      h2 = "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      ul
        - @event.errors.full_messages.each do |message|
          li = message

  .actions = f.submit

app/views/events/edit.html.slim
h1 Editing event

== render 'form'

=> link_to 'Show', @event
'|
=< link_to 'Back', events_path

app/views/events/index.html.erb
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#">EX<i class="fa fa-circle"></i>PANDA
				</a>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav navbar-right">
					<li ><%= link_to "HOME", root_path %></li>
					<li ><%= link_to "EVENT", events_path %></li>
					<!--<li><a href="Registration.html">REGISTRATION</a></li>-->
				</ul>
			</div>
		</div>
	</div>

	<!-- headerwrap -->
	<!-- <div id="headerwrap">
		<div class="container">
			<div class="row centered">
				<div class="col-lg-8 col-lg-offset-2">
					<h1>
						今までに無い、<b>新しい経験をしよう</b>
					</h1>
					<h2>EXPANDAで世界が広がる</h2>
				</div>
			</div>
		</div>
	</div>-->

	<!-- container -->
	<div class="container desc">
		<!-- 		<div class="row">
			<br>
			<br>
			<div class="col-lg-6 centered">
				<img src="img/friends.jpg" alt="" width="500px" height="400px">
			</div> -->
		<!-- col-lg-6 -->
		<!-- <div class="col-lg-6">
				<h4>LGBTの会 vol.4</h4>
				<p>82新宿三丁目店　[東京都]</p>
				<p>友達の友達は皆友達、という名目で始めた会ですが、好評につき今回第４回目となります！Lesbian, Bisexual の方を中心とした20代〜40代女性が40〜50名ほど、貸切のアイリッシュパブに集まり、話したい人は話す、飲みたい人は飲む(美味しいビールやカクテルが飲み放題)、食べたい人は食べる(美味しいフィッシュ&チップスやピザ！)という、とても自由な雰囲気の会になっています。
				<p>
					<i class="fa fa-circle-o"></i>参加費：3,000円<br />
					<i class="fa fa-link"></i> <a href="Event.html">Event.html</a>
				</p>
			</div>
		</div>

		<br>
		<br>
		<hr>
		<br>
		<br> -->
		<div class="row">
			<h3>12月3日（水）AM</h3>
			<div class="col-lg-6 centered">

				<img src="img/camping.jpg" alt="" width="500px" height="400px">
			</div>
			<!-- col-lg-6 -->
			<div class="col-lg-6">
				<h4>キレイな星空の下でキャンプ</h4>
				<p>カヤの平高原キャンプ場　[長野県]</p>
				<p>自然休養林に指定されているカヤの平高原は、標高1400～1700mに広がる高原です。ブナの原生林や高原植物もみられる自然の中のキャンプ場です。標高が高いので空気が澄んでいて、好天の日なら落ちてきそうなぐらいの満天の星を見ることができます。普段見慣れない星空で感動すること間違いないでしょう。明け方は幻想的な景色にまた感動します。</p>
				<p>
					<i class="fa fa-circle-o"></i>参加費：2,000円<br />
					<i class="fa fa-circle-o"></i>※移動費、食費は含まれません<br />
					<i class="fa fa-link"></i> <a href="Event.html">Event.html</a>
				</p>
				<div>
						<%= link_to "FOR MORE", event_path(1) %>
					</div>
			</div>
		</div>
		<br>
		<br>
		<hr>
		<br>
		<br>
		<div class="row">
			<h3>12月20日（金）AM&PM</h3>
			<div class="col-lg-6 centered">
				<img src="img/movie.jpg" alt="" width="500px" height="400px">
			</div>
			<!-- col-lg-6 -->
			<div class="col-lg-6">
				<h4>映画鑑賞＋座談会</h4>
				<p>TOHOシネマズ 新宿　[東京都]</p>
				<p>今話題の「アクアマン」をみんなで観に行きましょう。DCコミックス原作のヒーローで、「ジャスティス・リーグ」にも参戦したアクアマンを主役に描くアクション大作。人気テレビシリーズ「ゲーム・オブ・スローンズ」で知られるハワイ出身の俳優ジェイソン・モモアがタイトルロールのアクアマンを演じ、共演にニコール・キッドマンも。鑑賞後、簡単な座談会を予定してます。</p>
				<p>
					<i class="fa fa-circle-o"></i>参加費：500円<br />
					<i class="fa fa-circle-o"></i>※映画チケット費、食費は含まれません<br />
					<i class="fa fa-link"></i> <a href="Event.html">Event.html</a>
				</p>
			</div>
		</div>
		<br>
		<br>
	</div>

	<!-- FOOTER 上-->
	<div id="r">
		<div class="container">
			<div class="row centered">
			</div>
		</div>
	</div>

	<!-- FOOTER -->
	<div id="copyrights">
		<div class="container">
			<p>
				<strong>EXPANDA</strong>
			</p>
		</div>
	</div>

app/views/events/new.html.erb
	<!-- Fixed navbar -->
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="Top.html">EX<i class="fa fa-circle"></i>PANDA
				</a>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav navbar-right">
					<li><%= link_to "HOME", root_path %></li>
					<li><%= link_to "EVENT", events_path %></li>
					<!--<li class="active"><a href="Registration.html">REGISTRATION</a></li>-->
				</ul>
			</div>
		</div>
	</div>

	<div id="headerwrap">
		<div class="container">
			<div class="row centered">
				<div class="col-lg-8 col-lg-offset-2">
					<h1>
						<b>Register Your EVENT</b>
					</h1>
				</div>
			</div>
		</div>
	</div>

	<!-- from -->
	<div class="container w">

		<form class="" action="" method="post">
			<h4>イベントのタイトルを入力してください</h4>
			<input type="text" name="title" size="30" maxlength="20">
			<br>
			<br>
			<h4>イベントの内容を入力してください</h4>
			<textarea rows="10" cols="60">ここに記入してください</textarea>
			<br>
			<br>
			<h4>参加費</h4>
			<input type="text" name="parice" placeholder="¥" size="30" maxlength="20">
			<br>
			<br>
			<h4>日時</h4>
			<input type="date" name="example2" value="2019-03-17">

			<form class="from_Style" action="" method="post">
				<label for="field1"> <span>時間帯</span> <select name="時間帯">
						<option value="mny">AM</option>
						<option value="mny2">PM</option>
						<option value="mny3">AM&PM</option>
					</select>
				</label>
				<br>
				<br>
				<div>
					<a href="event_detail.html"><button type="button" >登録</button></a>
					<br>
					<br>
				</div>
				</main>
	</div>
	</form>
	</div>

	<!-- FOOTER 上-->
	<div id="r">
		<div class="container">
			<div class="row centered"></div>
		</div>
	</div>

	<!-- FOOTER -->
	<div id="f">
		<div class="container">
			<div class="row centered">
				<a href="https://twitter.com/"><i class="fa fa-twitter"></i></a><a href="https://www.facebook.com/"><i class="fa fa-facebook"></i></a><a
				 href="https://dribbble.com/"><i class="fa fa-dribbble"></i></a>
			</div>
		</div>
	</div>

	<div id="copyrights">
		<div class="container">
			<p>
				<strong>EXPANDA</strong>
			</p>
		</div>
	</div>

app/views/events/show.html.erb
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#">EX<i class="fa fa-circle"></i>PANDA
				</a>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav navbar-right">
					<li class="active"><%= link_to "HOME", root_path %></li>
					<li><%= link_to "EVENT", events_path %></li>
					<!--<li><a href="Registration.html">REGISTRATION</a></li>-->
				</ul>
			</div>
		</div>
	</div>

	<!-- headerwrap -->
	<!--
	<div id="headerwrap">
		<div class="container">
			<div class="row centered">
				<div class="col-lg-8 col-lg-offset-2">
					<h1>
						今までに無い、<b>新しい経験をしよう</b>
					</h1>
					<h2>EXPANDAで世界が広がる</h2>
				</div>
			</div>
		</div>
	</div>
-->
	<!-- container -->
	<div class="container desc">
		<!-- 		<div class="row">
			<br>
			<br>
			<div class="col-lg-6 centered">
				<img src="img/friends.jpg" alt="" width="500px" height="400px">
			</div>-->
		<!-- col-lg-6 -->
		<!--<div class="col-lg-6">
				<h4>LGBTの会 vol.4</h4>
				<p>82新宿三丁目店　[東京都]</p>
				<p>友達の友達は皆友達、という名目で始めた会ですが、好評につき今回第４回目となります！Lesbian, Bisexual の方を中心とした20代〜40代女性が40〜50名ほど、貸切のアイリッシュパブに集まり、話したい人は話す、飲みたい人は飲む(美味しいビールやカクテルが飲み放題)、食べたい人は食べる(美味しいフィッシュ&チップスやピザ！)という、とても自由な雰囲気の会になっています。
				<p>
					<i class="fa fa-circle-o"></i>参加費：3,000円<br />
					<i class="fa fa-link"></i> <a href="Event.html">Event.html</a>
				</p>
			</div>
		</div>

		<br>
		<br>
		<hr>
		<br>
		<br>
		<div class="row">
			<div class="col-lg-6 centered">
				<img src="img/movie.jpg" alt="" width="500px" height="400px">
			</div>-->
		<!-- col-lg-6 -->
		<!-- <div class="col-lg-6">
				<h4>映画鑑賞＋座談会</h4>
				<p>TOHOシネマズ 新宿　[東京都]</p>
				<p>今話題の「アクアマン」をみんなで観に行きましょう。DCコミックス原作のヒーローで、「ジャスティス・リーグ」にも参戦したアクアマンを主役に描くアクション大作。人気テレビシリーズ「ゲーム・オブ・スローンズ」で知られるハワイ出身の俳優ジェイソン・モモアがタイトルロールのアクアマンを演じ、共演にニコール・キッドマンも。鑑賞後、簡単な座談会を予定してます。</p>
				<p>
					<i class="fa fa-circle-o"></i>参加費：500円<br />
					<i class="fa fa-circle-o"></i>※映画チケット費、食費は含まれません<br />
					<i class="fa fa-link"></i> <a href="Event.html">Event.html</a>
				</p>
			</div>
		</div>

		<br>-->
		<br>
		<br>
		<div class="row">
			<div class="col-lg-6 centered">
				<img src="img/camping.jpg" alt="" width="500px" height="400px">
			</div>
			<!-- col-lg-6 -->
			<div class="col-lg-6">
				<h4>キレイな星空の下でキャンプ</h4>
				<p>カヤの平高原キャンプ場　[長野県]</p>
				<p>自然休養林に指定されているカヤの平高原は、標高1400～1700mに広がる高原です。ブナの原生林や高原植物もみられる自然の中のキャンプ場です。標高が高いので空気が澄んでいて、好天の日なら落ちてきそうなぐらいの満天の星を見ることができます。普段見慣れない星空で感動すること間違いないでしょう。明け方は幻想的な景色にまた感動します。</p>
				<p>
					<i class="fa fa-circle-o"></i>参加費：2,000円<br />
					<i class="fa fa-circle-o"></i>※移動費、食費は含まれません<br />
					<i class="fa fa-link"></i> <a href="Event.html">Event.html</a>
				</p>
			</div>
		</div>

		<!-- ユーザアイコン-->
		<div class="row">
			<img src="img/pic.jpg" alt="" width="40px">
			<img src="img/pic2.jpg" alt="" width="40px">
			<img src="img/pic3.jpg" alt="" width="40px">
			<img src="img/pic4.jpg" alt="" width="40px">
		</div>
		<br>
		<br>



		<!-- チャット部分-->
		<!-- 自分やユーザーの情報 -->
		<!--<h3 id="me" user_id="1">あなたはユーザー1です</h3>
<h3 id="partner" thread_id="1">相手</h3>
<div id="users">
	<button class="user" user_id="2">ユーザー2</button>
</div>-->
		<br>
		<div id="your_container">

			<!-- チャットの外側部分① -->
			<div id="bms_messages_container">
				<!-- ヘッダー部分② -->
				<div id="bms_chat_header">
					<!--ステータス-->
					<div id="bms_chat_user_status">
						<!--ユーザー名-->
						<div id="bms_chat_user_name">ChatRoom</div>
					</div>
				</div>

				<!-- タイムライン部分③ -->
				<div id="bms_messages">

					<!--メッセージ１（左側）-->
					<div class="bms_message bms_left">
						<div class="bms_message_box">
							<div class="bms_message_content">
								<div class="bms_message_text">移動はどのようにすればよいでしょうか</div>
							</div>
						</div>
					</div>
					<div class="bms_clear"></div><!-- 回り込みを解除（スタイルはcssで充てる） -->

					<!--メッセージ２（右側）-->
					<div class="bms_message bms_right">
						<div class="bms_message_box">
							<div class="bms_message_content">
								<div class="bms_message_text">電車でも車でも参加できます</div>
							</div>
						</div>
					</div>
					<div class="bms_clear"></div><!-- 回り込みを解除（スタイルはcssで充てる） -->
				</div>

				<!-- テキストボックス、送信ボタン④ -->
				<div id="bms_send">
					<textarea id="bms_send_message"></textarea>
					<div id="bms_send_btn">send</div>
				</div>
			</div>
		</div>
		<br>
		<br>
	</div>
	<br>
	<br>

	<!-- FOOTER 上-->
	<div id="r">
		<div class="container">
			<div class="row centered">
			</div>
		</div>
	</div>

	<!-- FOOTER -->
	<div id="copyrights">
		<div class="container">
			<p>
				<strong>EXPANDA</strong>
			</p>
		</div>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Expanda</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/schedules/_form.html.slim
= form_for @schedule do |f|
  - if @schedule.errors.any?
    #error_explanation
      h2 = "#{pluralize(@schedule.errors.count, "error")} prohibited this schedule from being saved:"
      ul
        - @schedule.errors.full_messages.each do |message|
          li = message

  .actions = f.submit

app/views/schedules/edit.html.slim
h1 Editing schedule

== render 'form'

=> link_to 'Show', @schedule
'|
=< link_to 'Back', schedules_path

app/views/schedules/index.html.slim
h1 Listing schedules

table
  thead
    tr
      th
      th
      th

  tbody
    - @schedules.each do |schedule|
      tr
        td = link_to 'Show', schedule
        td = link_to 'Edit', edit_schedule_path(schedule)
        td = link_to 'Destroy', schedule, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Schedule', new_schedule_path

app/views/schedules/show.html.slim
p#notice = notice


=> link_to 'Edit', edit_schedule_path(@schedule)
'|
=< link_to 'Back', schedules_path

app/views/top/index.html.erb
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse"
					data-target=".navbar-collapse">
					<span class="icon-bar"></span> <span class="icon-bar"></span> <span
						class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#">EX<i class="fa fa-circle"></i>PANDA
				</a>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav navbar-right">
					<li class="active"><%= link_to "HOME", root_path %></li>
					<li><%= link_to "EVENT", events_path %></li>
					<li><%= link_to "REGISTRATION", omniauth_authorize_path(User, 'facebook') %></li>
				</ul>
			</div>
		</div>
	</div>

	<!-- headerwrap -->
	<div id="headerwrap">
		<div class="container">
			<div class="row centered">
				<div class="col-lg-8 col-lg-offset-2">
					<h1>
						今までに無い、<b>新しい経験をしよう</b>
					</h1>
					<h2>EXPANDAで世界が広がる</h2>
				</div>
			</div>
		</div>
	</div>

	<!-- container -->
	<div class="container desc">
		<div class="row">
			<br>
			<br>
			<div class="col-lg-6 centered">
				<img src="img/friends.jpg" alt="" width="500px" height="400px">
			</div>
			<!-- col-lg-6 -->
			<div class="col-lg-6">
				<h4>LGBTの会 vol.4</h4>
				<p>82新宿三丁目店　[東京都]</p>
				<p>友達の友達は皆友達、という名目で始めた会ですが、好評につき今回第４回目となります！Lesbian, Bisexual の方を中心とした20代〜40代女性が40〜50名ほど、貸切のアイリッシュパブに集まり、話したい人は話す、飲みたい人は飲む(美味しいビールやカクテルが飲み放題)、食べたい人は食べる(美味しいフィッシュ&チップスやピザ！)という、とても自由な雰囲気の会になっています。
				<p>
					<i class="fa fa-circle-o"></i>参加費：3,000円<br />
					<i class="fa fa-link"></i> <a href="Event.html">Event.html</a>
				</p>
			</div>
		</div>

		<br>
		<br>
		<hr>
		<br>
		<br>
		<div class="row">
			<div class="col-lg-6 centered">
				<img src="img/movie.jpg" alt="" width="500px" height="400px">
			</div>
			<!-- col-lg-6 -->
			<div class="col-lg-6">
				<h4>映画鑑賞＋座談会</h4>
				<p>TOHOシネマズ 新宿　[東京都]</p>
				<p>今話題の「アクアマン」をみんなで観に行きましょう。DCコミックス原作のヒーローで、「ジャスティス・リーグ」にも参戦したアクアマンを主役に描くアクション大作。人気テレビシリーズ「ゲーム・オブ・スローンズ」で知られるハワイ出身の俳優ジェイソン・モモアがタイトルロールのアクアマンを演じ、共演にニコール・キッドマンも。鑑賞後、簡単な座談会を予定してます。</p>
				<p>
					<i class="fa fa-circle-o"></i>参加費：500円<br />
					<i class="fa fa-circle-o"></i>※映画チケット費、食費は含まれません<br />
					<i class="fa fa-link"></i> <a href="Event.html">Event.html</a>
				</p>
			</div>
		</div>

		<br>
		<br>
		<hr>
		<br>
		<br>
		<div class="row">
			<div class="col-lg-6 centered">
				<img src="img/camping.jpg" alt="" width="500px" height="400px">
			</div>
			<!-- col-lg-6 -->
			<div class="col-lg-6">
				<h4>キレイな星空の下でキャンプ</h4>
				<p>カヤの平高原キャンプ場　[長野県]</p>
				<p>自然休養林に指定されているカヤの平高原は、標高1400～1700mに広がる高原です。ブナの原生林や高原植物もみられる自然の中のキャンプ場です。標高が高いので空気が澄んでいて、好天の日なら落ちてきそうなぐらいの満天の星を見ることができます。普段見慣れない星空で感動すること間違いないでしょう。明け方は幻想的な景色にまた感動します。</p>
				<p>
					<i class="fa fa-circle-o"></i>参加費：2,000円<br />
					<i class="fa fa-circle-o"></i>※移動費、食費は含まれません<br />
					<i class="fa fa-link"></i> <a href="Event.html">Event.html</a>
				</p>
			</div>
		</div>
		<br>
		<br>
	</div>

	<!-- FOOTER 上-->
	<div id="r">
		<div class="container">
			<div class="row centered">
			</div>
		</div>
	</div>

	<!-- FOOTER -->
	<div id="copyrights">
		<div class="container">
			<p>
				<strong>EXPANDA</strong>
			</p>
		</div>
	</div>